# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).ready ->
  if $('#map')[0]
    d = undefined
    gmst = undefined
    handler = undefined
    latitude = undefined
    longitude = undefined
    n = undefined
    positionAndVelocity = undefined
    positionEci = undefined
    positionGd = undefined
    satrec = undefined
    timeSinceTleEpochMinutes = undefined
    tleLine1 = undefined
    tleLine2 = undefined
    velocityEci = undefined
    d = new Date
    n = d.getTime()
    timeSinceTleEpochMinutes = n / 60000
    tleLine1 = $('#tle1').text()
    tleLine2 = $('#tle2').text()
    satrec = satellite.twoline2satrec(tleLine1, tleLine2)
    positionAndVelocity = satellite.propagate(satrec, new Date)
    positionEci = positionAndVelocity.position
    velocityEci = positionAndVelocity.velocity
    gmst = satellite.gstimeFromDate(new Date)
    positionGd = satellite.eciToGeodetic(positionEci, gmst)
    longitude = positionGd.longitude
    latitude = positionGd.latitude
    console.log longitude
    console.log latitude
    console.log positionGd
    handler = undefined
    handler = Gmaps.build('Google')
    return handler.buildMap({
      provider: maxZoom: 3
      internal: id: 'map'
    }, ->
      markers = undefined
      markers = undefined
      markers = undefined
      markers = handler.addMarkers([ {
        'lat': latitude
        'lng': longitude
      } ])
      handler.bounds.extendWith markers
      handler.fitMapToBounds()
      return
    )
  return
# ---
# generated by coffee-script 1.9.2
